todo/app/urls.py
from . import views
from django.urls import path

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('delete/<int:id>/', views.delete, name="delete"),
    path('update/<int:id>/', views.update, name='update'),
    path('cbvhome/', views.Listview.as_view(), name='cbvhome'),
    path('details/<int:pk>/', views.Detailsview.as_view(), name='details'),
    path('cbupdate/<int:pk>/', views.Editview.as_view(), name='cbupdate'),
    path('cbdelete/<int:pk>/', views.Delete.as_view(), name='cbdelete')
]

todo/todo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/app/models.py
from django.db import models

# Create your models here.
class TODO(models.Model):
    task=models.CharField(max_length=250)
    priority=models.IntegerField()
    date=models.DateField()

    def __str__(self):
        return self.task

todo/app/forms.py
from django import forms
from .models import TODO


class Form(forms.ModelForm):
    class Meta:
        model = TODO
        fields = ['task', 'priority', 'date']

todo/app/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from .models import TODO
from .forms import Form
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView,DeleteView


# Create your views here.
class Listview(ListView):
    model = TODO
    template_name = 'index.html'
    context_object_name = 'data'


class Detailsview(DetailView):
    model = TODO
    template_name = 'details.html'
    context_object_name = 'task'


class Editview(UpdateView):
    model = TODO
    template_name = 'update.html'
    context_object_name = 'task'
    fields = ('task', 'priority', 'date')

    def get_success_url(self):
        return reverse_lazy('app:details', kwargs={'pk': self.object.id})


class Delete(DeleteView):
    model = TODO
    template_name = 'delete.html'
    success_url = reverse_lazy('app:cbvhome')


def index(request):
    value = TODO.objects.all()
    if request.method == 'POST':
        name = request.POST.get('task', '')
        priority = request.POST.get('priority', '')
        date = request.POST.get('date', '')
        task = TODO(task=name, priority=priority, date=date)
        task.save()
    return render(request, 'index.html', {'data': value})


def delete(request, id):
    value = TODO.objects.get(id=id)
    if request.method == 'POST':
        value.delete()
        return redirect('/')
    return render(request, 'delete.html')


def update(request, id):
    id = TODO.objects.get(id=id)
    form_data = Form(request.POST or None, instance=id)
    if form_data.is_valid():
        form_data.save()
        return redirect('/')
    return render(request, 'edit.html', {'form': form_data, 'id': id})

todo/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TODO PROJECT</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
{% block content %}

{% endblock %}
</body>
</html>

todo/templates/delete.html
{% extends 'base.html' %}
    {% block content %}
        <form method="POST">
            {% csrf_token %}
            <h2>Are u sure want to delete ?</h2>
            <input type="submit" class="btn btn-primary">
        </form>

    {% endblock %}

todo/templates/details.html
{% extends 'base.html' %}
    {% block content %}
        <div class="shadow card">
            <div class="card-body">
                <h5 class="card-title">{{task.task}}</h5>
                <p class="card-text">{{task.priority}}</p>
                <p>{{task.date}}</p>
                <a href="{% url 'app:delete' task.id %}" class="btn btn-primary">DONE</a>
                <a href="{% url 'app:update' task.id %}" class="btn btn-danger">UPDATE</a>
            </div>
        </div>
    {% endblock %}

todo/templates/edit.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">SUBMIT</button>
</form>
{% endblock %}

todo/templates/index.html
{% extends 'base.html' %}
    {% block content %}
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="banner">
                        <div class="banner-text">
                            <h2>TODO APP</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <form method="POST" class="p-3 shadow">
                         {% csrf_token %}
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Task name" name="task" >
                        </div>
                        <div class="form-group">
                            <input type="number" class="form-control" placeholder="Priority" name="priority">
                        </div>
                        <div class="form-group">
                            <input type="date" class="form-control" placeholder="Date" name="date">
                        </div>
                        <br>
                        <input type="submit" class="btn btn-success">
                    </form>
                </div>
                <div class="col-md-6">
                    <h2>Task to be completed</h2>
                    {% for i in data %}
                        <div class="shadow card">
                            <div class="card-body">
                                <h5 class="card-title">{{i.task}}</h5>
                                <p class="card-text">{{i.priority}}</p>
                                <p>{{i.date}}</p>
                                <a href="{% url 'app:delete' i.id %}" class="btn btn-primary">DONE</a>
                                <a href="{% url 'app:update' i.id %}" class="btn btn-danger">UPDATE</a>
                            </div>
                        </div>
                    <br>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% endblock %}

todo/templates/update.html
{% extends 'base.html' %}
    {% block content %}
        <div class="card">
            <div class="card-title">
                Task Update
            </div>
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button type="submit">SUBMIT</button>
                </form>
            </div>
        </div>
    {% endblock %}